# Generated by Django 3.1.13 on 2022-03-25 21:55

import classification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('retweets_count', models.IntegerField(null=True)),
                ('likes_count', models.IntegerField(null=True)),
                ('followers_count', models.IntegerField(null=True)),
                ('friends_count', models.IntegerField(null=True)),
                ('statuses_count', models.IntegerField(null=True)),
                ('verified', models.BooleanField(default=False, null=True)),
                ('profile_image_url', models.CharField(max_length=255, null=True)),
                ('profile_banner_url', models.CharField(max_length=255, null=True)),
                ('profile_background_image_url', models.CharField(max_length=255, null=True)),
                ('score', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.SmallIntegerField(choices=[('SATU', 1), ('DUA', 2), ('TIGA', 3), ('EMPAT', 4)], default=classification.models.ModelType['DUA'], null=True)),
                ('threshold', models.SmallIntegerField(null=True)),
                ('accuracy_score', models.FloatField(null=True)),
                ('confusion_matrix', models.FloatField(null=True)),
                ('precision_score', models.FloatField(null=True)),
                ('recall', models.FloatField(null=True)),
                ('f1', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uids', models.CharField(max_length=100)),
                ('profile_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('geo', models.CharField(max_length=20, null=True)),
                ('likes_count', models.IntegerField(null=True)),
                ('hashtags', models.JSONField(null=True)),
                ('conversation_id', models.CharField(max_length=100, null=True)),
                ('urls', models.JSONField(null=True)),
                ('mentions', models.JSONField(null=True)),
                ('tweet', models.TextField()),
                ('timezone', models.CharField(max_length=20, null=True)),
                ('place', models.CharField(max_length=100, null=True)),
                ('photos', models.JSONField(null=True)),
                ('replies_count', models.IntegerField(null=True)),
                ('retweets_count', models.IntegerField(null=True)),
                ('cashtags', models.JSONField(null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('retweet', models.BooleanField(default=False, null=True)),
                ('quote_url', models.CharField(max_length=100, null=True)),
                ('video', models.IntegerField(null=True)),
                ('user_rt_id', models.CharField(max_length=100, null=True)),
                ('near', models.CharField(max_length=100, null=True)),
                ('source', models.CharField(max_length=100, null=True)),
                ('retweet_date', models.DateTimeField(null=True)),
                ('reply_to', models.JSONField(null=True)),
                ('sentiment', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'tweets',
            },
        ),
    ]
