# Generated by Django 4.0.3 on 2022-03-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='threshold',
            new_name='threshold_max',
        ),
        migrations.AddField(
            model_name='setting',
            name='threshold_min',
            field=models.SmallIntegerField(default=1, null=True),
        ),
    ]
