# Generated by Django 4.0.3 on 2022-03-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_setting_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='f1',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='precision_score',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='recall',
            field=models.JSONField(null=True),
        ),
    ]
