# Generated by Django 4.0.3 on 2022-03-31 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0004_alter_setting_f1_alter_setting_precision_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='f1',
            new_name='f1_score',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='recall',
            new_name='recall_score',
        ),
    ]
